# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: serverless-notification-microservice
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::notification-micro-service-logs/*"

    - Effect: Allow
      Action:
        - sns:Publish
        - sqs:*
      Resource: '*'

functions:
  sendNotification:
    handler: src/handler.sendNotification
    events:
      - http:
          path: send
          method: post
          cors: true

  processNotification:
    handler: src/handler.processNotification
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - NotificationSqsQueue
              - Arn

resources:
  Resources:
    NotificationSnsTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Notification

    NotificationSqsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: notification-queue

    NotificationSnsTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        Topics:
          - Ref: NotificationSnsTopic
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal: '*'
              Action: sns:Publish
              Resource: '*'
              Condition:
                ArnEquals:
                  aws:SourceArn:
                    Ref: NotificationSqsQueue

plugins:
  - serverless-offline